IMPORTAREA BIBLIOTECII

In [1]:
import numpy as np

CREAREA MATRICILOR

In [8]:
#creare printr-o lista de tuplu

my_list = [1,2,3,4]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [9]:
#creare prin frunctia arange care returneaza o matrice cu elemente uniform distantate

#np.arange(start, stop, step, dtype=None), interval [start; stop)
#start = prima valoare
#stop = ultima valoare
#step = pas
#dtype = tipul elementelor matricei de iesire
np.arange(7)
np.arange(2,7)
np.arange(1,7,2)
np.arange(start = 0, stop = 10, step = 2, dtype = None)

array([0, 2, 4, 6, 8])

In [12]:
#similar np.arange este np.linspace care se foloseste de numarul de elemente din interval
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
#matrice de zerouri de dimensiuni date
np.zeros(4) # 1 linie cu 4 coloane
np.zeros([4, 3]) # 4 linii cu 3 coloane

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#matrice de 1 cu dimensiuni date
np.ones(4)
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#matericea identitate de dimensiune data
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
#crearea unei matrice prin copierea alteia existente
a = np.array([1,2,3,4])
b = np.copy(a)
a[0] = 10
b = np.copy(a)
a
b

array([10,  2,  3,  4])

DIMENSIUNEA MATRICILOR

In [40]:
#aflarea dimensiunilor unei matrice
a = np.array([1,2,3,4])
b = np.array([ [1,2,3], [4,5,6] ])
#a.ndim
b.ndim

2

In [42]:
#aflarea formei unei matrice
a = np.array([1,2,3,4])
a.shape

b = np.array([[1,2,3,4], [5,6,7,8]])
b.shape

(2, 4)

In [55]:
#schimabrea formei unei matrici

x = np.array([ [1,2,3,4], [5,6,7,8] ])
x.reshape(4,2)
#x.reshape(2,4)
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
#aflarea numarului de elemente dintr-o matrice
a = np.array([1,2,3,4])
a.size
b = np.array([ [1,2,3,4], [5,6,7,8] ])
b.size

8

In [59]:
#transpusa unei matrici
a = np.array([ [4,6,2], [8,7,9] ])
a.transpose()


array([[4, 8],
       [6, 7],
       [2, 9]])

INDEXING SI SLICING

In [64]:
#selectarea unui element dintr-o matrice
a = np.array([1,2,3,4,5])
print(a[2])

b = np.array([[1,2,3,4], [5,6,7,8]])
b[1]
print(b[1][2])

3
7


In [65]:
#selectarea unui interval dintr-o matrice
a = np.array([1,2,3,4,5])
a[1:4] # = elementele cu indecsii 1,2 si 3 pentru ca intervalul este [1,4)

array([2, 3, 4])

In [71]:
#selectarea unor elemente din matrice pe baza unei conditii
a = np.arange(1,6)
a[a>3]
a[a>=3]

array([3, 4, 5])

In [72]:
#atribuirea de noi valori
a = np.arange(1,6)
a[1:3] = 10
a

array([ 1, 10, 10,  4,  5])

OPERATII CU MATRICI

In [77]:
#adunarea matricilor
a = np.array([ [1,3,4,5], [4,8,7,9] ])
b = np.array([ [1,1,1,1], [1,1,1,1] ])

np.add(a, 2) # = a+2
np.add (a,b) # = a+b

array([[ 2,  4,  5,  6],
       [ 5,  9,  8, 10]])

In [80]:
#scadere
a=np.array([[1,3,5,8],[2,3,7,9]])
b=np.array([[1,2,3,4],[5,6,7,8]])

np.subtract(a,1) # a-1
np.subtract(a,b) # a-b

array([[ 0,  1,  2,  4],
       [-3, -3,  0,  1]])

In [85]:
#inmultire
a=np.array([[1,3,5,8],[2,3,7,9]])
b=np.array([[1,2,3,4],[5,6,7,8]])

np.multiply(a,2) # = a*2
np.multiply(a,b) # = a*b element cu element
a ** b # element din a la puterea element din b de pe aceeasi pozitie

array([[       1,        9,      125,     4096],
       [      32,      729,   823543, 43046721]])

FUNCTII AGREGAT SI STATISTICE

In [88]:
#suma elementelor din matrice
a=np.array([[1,3,5,8],[2,3,7,9]])
print(a.sum())

38


In [90]:
#media elementelor unei matrice
a=np.array([[1,3,5,8],[2,3,7,9]])
print(a.mean())

4.75


In [91]:
#calcul deviatie standard a tuturor elementelor
a=np.array([[1,3,5,8],[2,3,7,9]])
a.std()

np.float64(2.7726341266023544)

In [92]:
#minimul elementelor
a=np.array([[1,3,5,8],[2,3,7,9]])
a.min()

np.int64(1)

In [93]:
#maximul elementelor
a=np.array([[1,3,5,8],[2,3,7,9]])
a.max()

np.int64(9)

In [96]:
#operatiile statistice se pot face si pe linii/coloane
#axis -> pus ca paramentru pentru fiecare funtie statistica
#axis = 1 -> pe linii
#axis = 0 -> pe coloane
a=np.array([[1,3,5,8],[2,3,7,9]])
a.sum(axis = 1) #si apar sumele facute pe fiecare linie in parte
a.sum(axis = 0) #si a[ar sumele facut pe fiecare coloana in parte


array([ 3,  6, 12, 17])